In [44]:
import numpy as np #linear algebra
import cv2
import pandas as pd # this is for inmporting files
import os

import matplotlib.pyplot as plt #ths is for graphing and presentation
import seaborn as sns

import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import random
from random import shuffle
from tqdm import tqdm

import tensorflow as tf
#from tflearn.layers.conv import conv_2d, max_pool_2d
#rom tflearn.layers.core import input_data, dropout, fully_connected
#from tflearn.layers.estimator import regression

# Preparing the dataset

#### Getting the image data 

In [45]:
#file = r"C:\Users\vhlungwane\Desktop\ACML project\Dataset"
file = "/home/vmuser/Desktop/Dataset"
Cat = ["Brad Pitt","Alia Bhatt","Anushka Sharma","Amitabh Bachchan","Andy Samberg","Alexandra Daddario","Brad Pitt","Ellen Degeneres","Hugh Jackman","Jessica Alba"]
#"Alia Bhatt""Amitabh Bachchan"
for category in Cat:
    data = []
    path = os.path.join(file, category)
    for img in os.listdir(path):
        img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
        new_array = cv2.resize(img_array, (50,50))
        data.append([np.array(new_array), labels(category)])
        print(data)
        plt.imshow(new_array, cmap="gray")
        plt.show()
        break
    break
    

TypeError: 'numpy.ndarray' object is not callable

### Making the labels(One-hot encoding)

#### This is the enrollment stage :

In [46]:
def labels(image_name):
    name = image_name
    if name == "Akshay Kumar":
        return np.array([1,0,0,0,0,0,0,0,0,0])
    elif name == "Alexandra Daddario":
        return np.array([0,1,0,0,0,0,0,0,0,0])
    elif name == "Alia Bhatt":
        return np.array([0,0,1,0,0,0,0,0,0,0])
    elif name == "Amitabh Bachchan":
        return np.array([0,0,0,1,0,0,0,0,0,0])
    elif name == "Andy Samberg":
        return np.array([0,0,0,0,1,0,0,0,0,0])
    elif name == "Anushka Sharma":
        return np.array([0,0,0,0,0,1,0,0,0,0])
    elif name == "Brad Pitt":
        return np.array([0,0,0,0,0,0,1,0,0,0])
    elif name == "Ellen Degeneres":
        return np.array([0,0,0,0,0,0,0,1,0,0])
    elif name == "Hugh Jackman":
        return np.array([0,0,0,0,0,0,0,0,1,0])
    elif name == "Jessica Alba":
        return np.array([0,0,0,0,0,0,0,0,0,1])

### Storing the image data into a vector

In [47]:
def features():
    data = []
    for category in Cat:
        path = os.path.join(file, category)
        for img in os.listdir(path):
            img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
            new_array = cv2.resize(img_array, (50,50))
            data.append([np.array(new_array), labels(category)])
            #plt.imshow(new_array, cmap="gray")
            #plt.show()
    return data

#### Checking the size of the data

In [48]:
data = features()

#### Shuffling the data

In [49]:

random.shuffle(data)


In [50]:
image = np.array([data[i][0] for i in range(len(data))])
labels = np.array([data[i][1] for i in range(len(data))])

### Splitting the dataset

In [51]:
image_S = np.split(image,[300, 400])
labels_S = np.split(labels,[300, 400])

X_train = image_S[0]
X_train = tf.expand_dims(X_train, axis=-1)
X_test = image_S[1]
X_test = tf.expand_dims(X_test, axis=-1)
X_validate = image_S[1]
X_validate = tf.expand_dims(X_validate, axis=-1)


Y_train = labels_S[0]
Y_test = labels_S[1]
Y_validate = labels_S[1]

### Dimesions of the dataset

In [52]:
print(X_train.shape)
print(X_test.shape)
print(X_validate.shape)
print(Y_train.shape)
print(Y_test.shape)
print(Y_validate.shape)

(300, 50, 50, 1)
(100, 50, 50, 1)
(100, 50, 50, 1)
(300, 10)
(100, 10)
(100, 10)


#### Presenting a sample from the dataset

In [53]:
for  i in data[:1]:
    print("This is a sample from the feature data")
    print(i[0])
    print("This is the corresponding sample from the label data")
    print(i[1])

This is a sample from the feature data
[[21 22 30 ... 85 83 78]
 [38 37 43 ... 83 77 69]
 [28 30 36 ... 85 85 82]
 ...
 [60 56 51 ... 70 53 29]
 [58 48 41 ... 70 53 30]
 [56 47 37 ... 68 49 24]]
This is the corresponding sample from the label data
[0 0 0 0 0 1 0 0 0 0]


#### Spliting the training data from the testing data

In [54]:
# def Plot_Training_Progress(history):
#     acc = history['accuracy']
#     val_acc = history['val_accuracy']
#     loss = history['loss']
#     val_loss = history['val_loss']
#     epochs = range(len(acc))

#     fig, axes = plt.subplots(1, 2, figsize=(25,10))
    
#     #Plot Accuracy
#     axes[0].plot(epochs, acc, 'b-', label='Training Accuracy')
#     axes[0].plot(epochs, val_acc, 'g--', label='Validation Accuracy')
#     axes[0].set_title('Training and Validation Accuracy')
#     axes[0].set_xlabel('Epoch')
#     axes[0].set_ylabel('Accuracy')
#     axes[0].legend(loc='best')

#     #Plot Loss
#     axes[1].plot(epochs, loss, 'b-', label='Training Loss')
#     axes[1].plot(epochs, val_loss, 'g--', label='Validation Loss')
#     axes[1].set_title('Training and Validation Loss')
#     axes[1].set_xlabel('Epoch')
#     axes[1].set_ylabel('Loss')
#     axes[1].legend(loc='best')

#     return plt

In [55]:
def normalize_features(X_train):
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)

    return X_train

In [56]:
#X_train = normalize_features(X_train)
#X_test = normalize_features(X_test)


# Build the model

#### Importing stuff

In [57]:
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D, AveragePooling2D
import pydot
import keras_tuner as kt
from keras_tuner import HyperModel
from keras_tuner.tuners import RandomSearch ,Hyperband

### Building the model

In [58]:
model = Sequential()
model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(50,50,1)))
#model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(50,50,1)))
model.add(MaxPooling2D(pool_size=(5,5)))
#model.add(Convolution2D(32,3,data_format='channels_last',activation='relu',input_shape=(50,50,1)))
model.add(Flatten())
model.add(Dense(2000))
model.add(Dense(3000))
model.add(Dense(40000))
#model.add(Dense(5000))
#model.add(Dense(6000))
model.add(Dropout(0.8))
#model.add(Convolution2D(10,3,data_format='channels_last',activation='relu',input_shape=(50,50,1)))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer = 'adadelta', metrics = ['accuracy'])

In [59]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 48, 48, 32)        320       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 9, 9, 32)          0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 2592)              0         
_________________________________________________________________
dense_10 (Dense)             (None, 2000)              5186000   
_________________________________________________________________
dense_11 (Dense)             (None, 3000)              6003000   
_________________________________________________________________
dense_12 (Dense)             (None, 40000)             120040000 
_________________________________________________________________
dropout_5 (Dropout)          (None, 40000)            

In [60]:
keras.utils.plot_model(model, to_file='Baseline_Model_Architecture.png', show_shapes=True, show_layer_names=True)


('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


#### Fit the model

In [61]:
Baseline_History = model.fit(X_train,Y_train,epochs = 10,validation_data=(X_validate,Y_validate))

Epoch 1/10
10/10 [==============================] - 1s 74ms/step - loss: 46.3005 - accuracy: 0.1252 - val_loss: 24.2724 - val_accuracy: 0.2000
Epoch 2/10
10/10 [==============================] - 1s 63ms/step - loss: 43.8317 - accuracy: 0.1366 - val_loss: 9.5906 - val_accuracy: 0.2000
Epoch 3/10
10/10 [==============================] - 1s 63ms/step - loss: 42.4673 - accuracy: 0.1178 - val_loss: 13.7078 - val_accuracy: 0.2000
Epoch 4/10
10/10 [==============================] - 1s 63ms/step - loss: 36.4322 - accuracy: 0.1533 - val_loss: 14.6277 - val_accuracy: 0.2100
Epoch 5/10
10/10 [==============================] - 1s 63ms/step - loss: 46.3808 - accuracy: 0.1158 - val_loss: 8.3176 - val_accuracy: 0.2600
Epoch 6/10
10/10 [==============================] - 1s 63ms/step - loss: 39.0704 - accuracy: 0.1957 - val_loss: 7.0508 - val_accuracy: 0.2500
Epoch 7/10
10/10 [==============================] - 1s 63ms/step - loss: 40.2493 - accuracy: 0.1148 - val_loss: 9.2511 - val_accuracy: 0.2100
Epo

In [62]:
# plt = Plot_Training_Progress(Baseline_History.history)   
# plt.savefig('Baseline_Plots.png', dpi=400)    
# plt.show()

In [63]:
testLoss, testAccuracy = model.evaluate(X_test,Y_test)

print("Testing Loss", testLoss)
print("Testing Accuracy", "{:.2%}" .format(testAccuracy))


4/4 [==============================] - 0s 6ms/step - loss: 5.8875 - accuracy: 0.3400
Testing Loss 5.887545108795166
Testing Accuracy 34.00%


In [64]:
class Face_hypermodel(HyperModel):
    def __init__(self, input_shape, num_classes):
        self.input_shape = input_shape
        self.num_classes = num_classes

    def build(self, hp):
        model = keras.Sequential()

        model.add(Convolution2D(filters=hp.Choice('Conv_Filters_1',values=[16, 32, 64],default=16),activation='relu',kernel_size=3, input_shape=self.input_shape))
        model.add(Convolution2D(filters=hp.Choice('Conv_Filters_2',values=[16, 32, 64],default=16), activation=hp.Choice('Conv_Activation_2',values=['relu', 'sigmoid'],default='relu'),kernel_size=3))
        model.add(MaxPooling2D(pool_size=2))
        model.add(Dropout(rate=hp.Float('Dropout_Rate_1',min_value=0.0,max_value=0.5,default=0.25,step=0.05)))

        model.add(Convolution2D(filters=hp.Choice('Conv_Filters_3',values=[32, 64, 128],default=32), activation=hp.Choice('Conv_Activation_3',values=['relu', 'sigmoid'],default='relu'),kernel_size=3))
        model.add(Convolution2D(filters=hp.Choice('Conv_Filters_4',values=[32, 64, 128],default=64), activation=hp.Choice('Conv_Activation_4',values=['relu', 'sigmoid'],default='relu'),kernel_size=3))
        model.add(AveragePooling2D(pool_size=2))
        model.add(Dropout(rate=hp.Float('Dropout_Rate_2',min_value=0.0,max_value=0.5,default=0.25,step=0.05)))

        model.add(Flatten())
        model.add(Dense(units=hp.Int('Last_Dense_NumUnits',min_value=16,max_value=128,step=16,default=64), activation='relu'))
        model.add(Dropout(rate=hp.Float('Dropout_Rate_3',min_value=0.0,max_value=0.5,default=0.25,step=0.05)))
        model.add(Dense(self.num_classes, activation='softmax'))

        model.compile(optimizer=keras.optimizers.Adam(hp.Float('Adam_Optim_LR',min_value=1e-4,max_value=1e-2,sampling='LOG',default=1e-3)),
            loss='categorical_crossentropy',
            metrics=['accuracy']
        )

        print("MODEL SUCCESSFULLY CREATED")

        return model

In [41]:


hyper_model = Face_hypermodel((50,50,1), 10)



In [42]:


maxTrials = 20
execPerTrial = 2
numEpochSearch = 10
seedValue = 2

model_tuner = RandomSearch(
    hyper_model,
    objective='val_accuracy',
    seed=seedValue,
    max_trials=maxTrials,
    executions_per_trial=execPerTrial,
    project_name='Face_HyperTuned'
)



INFO:tensorflow:Reloading Oracle from existing project ./Face_HyperTuned/oracle.json
MODEL SUCCESSFULLY CREATED
INFO:tensorflow:Reloading Tuner from ./Face_HyperTuned/tuner0.json


In [43]:
model_tuner.search(x=X_train, y=Y_train, epochs=numEpochSearch, validation_data=(X_validate, Y_validate))

INFO:tensorflow:Oracle triggered exit


In [80]:
model_tuner.results_summary()

Results summary
Results in ./Face_HyperTuned
Showing 10 best trials
Trial summary
Hyperparameters:
Conv_Filters_1: 16
Conv_Filters_2: 16
Conv_Activation_2: sigmoid
Dropout_Rate_1: 0.25
Conv_Filters_3: 32
Conv_Activation_3: relu
Conv_Filters_4: 128
Conv_Activation_4: relu
Dropout_Rate_2: 0.5
Last_Dense_NumUnits: 112
Dropout_Rate_3: 0.35000000000000003
Adam_Optim_LR: 0.0005674460859990781
Score: 0.4599999934434891
Trial summary
Hyperparameters:
Conv_Filters_1: 64
Conv_Filters_2: 32
Conv_Activation_2: sigmoid
Dropout_Rate_1: 0.2
Conv_Filters_3: 32
Conv_Activation_3: relu
Conv_Filters_4: 128
Conv_Activation_4: relu
Dropout_Rate_2: 0.45
Last_Dense_NumUnits: 48
Dropout_Rate_3: 0.05
Adam_Optim_LR: 0.00036276965095376624
Score: 0.39000000059604645
Trial summary
Hyperparameters:
Conv_Filters_1: 32
Conv_Filters_2: 64
Conv_Activation_2: relu
Dropout_Rate_1: 0.1
Conv_Filters_3: 32
Conv_Activation_3: sigmoid
Conv_Filters_4: 32
Conv_Activation_4: relu
Dropout_Rate_2: 0.25
Last_Dense_NumUnits: 64
Dro

### Confusion Matrix